[package]
name = "precrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.13"
umbral-pre = { version = "0.5.1", features = ["serde-support"] }
serde = "1.0.136"
serde_json = "1.0.78"
serde_bytes = "0.11.5"
indicatif = "0.16.2"